### ISSUE TITLE
Extend eslint to add custom rules

### ISSUE THREAD

**Issue by nzeugaa** [electrode-io/electrode-boilerplate-universal-react-node#35]
Hi, is there any way to extend eslint in order to add custom rules ? I've tried to add .eslintrc to the project but it's not used when running `gulp check`.
Thanks.

**Comment by caoyangs** [comment]
This will be fixed by https://github.com/electrode-io/electrode-archetype-react-app/pull/35

**Comment by ananavati** [comment]
closing this issue to keep the discussion centric to one issue on https://github.com/electrode-io/electrode-archetype-react-app/pull/35
