### ISSUE TITLE
gulp test-frontend-cov fails in Sierra

### ISSUE THREAD

**Issue by ibulmer** [electrode-io/electrode-boilerplate-universal-react-node#41]
Running gulp test-frontend-cov causes the error: [launcher]: Cannot start PhantomJS

This appears to be caused be a 1.x version of PhantomJs instead of 2.x. The latest version of electrode-archetype-react-app-dev seems to be installing PhantomJs version 1.9. 

To fix this I added PhantomJs  version 2.1.7 to my dev dependencies and installed it. It fixes the issue. 

It really seems like this should fixed somewhere in the electrode-archetype-react-app-dev, so that phantom 2.x is installed instead of phantom 1.x when electrode-archetype-react-app-dev is being installed.

**Comment by ananavati** [comment]
fix for updating Phantom to 2.x.x is part of this pr: https://github.com/electrode-io/electrode-archetype-react-app/pull/34

next version update for `electrode-archetype-react-app` & `electrode-archetype-react-app-dev` is scheduled for the end of this week 11/11 and it will include the upgrade to PhantomJS 2.x.x

**Comment by ananavati** [comment]
duplicate issue here: https://github.com/electrode-io/electrode-io.github.io/issues/312

**Comment by ananavati** [comment]
published 
```
+ electrode-archetype-react-app@1.3.3
+ electrode-archetype-react-app-dev@1.3.3
```

@ibulmer can you please try out with the patch release of `electrode-archetype-react-app` and   ` electrode-archetype-react-app-dev` and close this bug if your issue is resolved

**Comment by ananavati** [comment]
<img width="881" alt="screen shot 2016-11-17 at 9 38 03 am" src="https://cloud.githubusercontent.com/assets/360041/20400460/9e207f10-aca9-11e6-86a8-47878baac19d.png">
