### ISSUE TITLE
how to add parser to css

### ISSUE THREAD

**Issue by CoffiDev** [electrode-io/electrode-boilerplate-universal-react-node#42]
Hi, I want to add Sugar CSS, because I notice that the logic to add the css loaders is in electrode-archetype-react-app/config/webpack/partial/extract.js, and I tried to just add the parser after postcssLoader:

`var cssQuery = cssLoader + "?modules&-autoprefixer!" + postcssLoader + "?parser=sugarss";`

But when I do this the gulp dev server display: 
"**webpack bundle is now VALID but has ERRORS**" 
and no content is rendered.

So how I can add parameters to the postcssLoader and how I can add plugins? thanks for your time.

**Comment by ananavati** [comment]
@CoffiDev thanks for checking out electrode. 

Electrode by **default/only** supports next generation CSS technologies CSSNext syntax for CSS but we will look into the feasibility of adding `sugarss` and how well it plays with CSSNext syntax.
