### ISSUE TITLE
Logging mechanism in electrode

### ISSUE THREAD

**Issue by bubuzzz** [electrode-io/electrode-boilerplate-universal-react-node#45]
I cannot find any repository / documentation under electrode.io for the logging. Is there any suggestion for this or do i have to use other 3rd party node library like winston in order to do so ?

**Comment by ananavati** [comment]
@bubuzzz 

There are no examples of logging on OSS electrode modules but any 3rd party loggers like winston should work just fine.

**Comment by bubuzzz** [comment]
thank @ananavati , i will integrate good plugin to electrode. Feel free to close this ticket
